version: "3.7"
services:
  audio-converter:
    image: dockerregistry.domain.com/audio-converter:latest
    container_name: audio-converter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/media
      - ./:/config
    environment:
      - AUDIO_CODEC_DESTINATION=ac3
      - AUDIO_CODECS_TO_CONVERT=truehd, eac3
      - WAIT_BETWEEN_SCANS_IN_SECONDS=43200
      - EMAIL_CONFIG_FROM_EMAIL_ADDRESS=username@gmail.com
      - EMAIL_CONFIG_TO_EMAIL_ADDRESSES=username@gmail.com
      - EMAIL_CONFIG_USERNAME=username@gmail.com
      - EMAIL_CONFIG_PASSWORD=Password
      - EMAIL_CONFIG_SMTP_SERVER=smtp.gmail.com
      - EMAIL_CONFIG_SMTP_PORT=465
      - EMAIL_CONFIG_SEND_TEST_EMAIL=false
    restart: always
