services:
  audio-converter:
    image: dockerregistry.domain.com/audio-converter:latest
    container_name: audio-converter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/media
      - ./:/config
    environment:
      - EMAIL_PASSWORD=Password
    restart: always
