version: "3.7"
services:
  audio-fixer:
    image: dockerregistry.domain.com/audio-fixer:latest
    container_name: audio-fixer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/media
      - ./:/config
    environment:
      - WAIT_BETWEEN_SCANS_IN_SECONDS=43200
      - PROBLEMATIC_AUDIO_FORMATS=truehd, eac3
      - AMENDED_AUDIO_FORMAT=ac3
      - EMAIL_CONFIG_FROM_EMAIL_ADDRESS=username@gmail.com
      - EMAIL_CONFIG_TO_EMAIL_ADDRESSES=username@gmail.com
      - EMAIL_CONFIG_USERNAME=username@gmail.com
      - EMAIL_CONFIG_PASSWORD=Password
      - EMAIL_CONFIG_SMTP_SERVER=smtp.gmail.com
      - EMAIL_CONFIG_SMTP_PORT=465
      - EMAIL_CONFIG_SEND_TEST_EMAIL=false
    restart: always
