version: "3.7"
services:
  audio-fixer:
    image: audio-fixer:latest
    container_name: audio-fixer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/media
      - ./:/config
    environment:
      - WAIT_BETWEEN_SCANS_IN_SECONDS=43200
      - PROBLEMATIC_AUDIO_FORMATS=truehd, eac3
      - AMENDED_AUDIO_FORMAT=ac3
    restart: always
