settings:
  conversion:
    - wait_between_scans_in_seconds: 43200
    - directories:
        - path: /media/folder1
          from: eac3
          to: ac3
        - path: /media/folder2
          from:
            - truehd
            - eac3
          to: mp3
  email:
    - host: smtp.gmail.com
    - port: 465
    - to: username@gmail.com
    - sender: username@gmail.com
    - username: username@gmail.com
    - password: password
    - send_test_email_on_start: false
